### ISSUE TITLE
hmy cli returns library not found

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/pangaea-ops#1]
so trying to fetch balances from an address: 
luka@ubuntu:~/Desktop/pangaea$ ./hmy --chain-id="testnet" --node="https://api.s1.b.hmny.io/" balances one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw
./hmy: error while loading shared libraries: libbls384_256.so: cannot open shared object file: No such file or directory
luka@ubuntu:~/Desktop/pangaea$ ./hmy --node="https://api.s1.b.hmny.io/" balances one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw
./hmy: error while loading shared libraries: libbls384_256.so: cannot open shared object file: No such file or directory
luka@ubuntu:~/Desktop/pangaea$ ls
51c72356e9e774cfa61a4e857e0867b055763a41019033cc114c77b2274026b825a7b7036976002c279d47289c26cd81.key
hmy
hmy.sh
libbls384_256.so
libcrypto.so.10
libgmp.so.10
libgmpxx.so.4
libmcl.so
wallet
wallet.sh
luka@ubuntu:~/Desktop/pangaea$

Doesnt find the library file even though its in the same directory (installed via -d command).

works with this command though: 
luka@ubuntu:~/Desktop/pangaea$ LD_LIBRARY_PATH=.  ./hmy --node="https://api.s1.b.hmny.io/" balance one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw
result: []

**Comment by fxfactorial** [comment]
there is a difference between `./hmy` and `./hmy.sh`, can you try the initial command with 

```
./hmy.sh balances  --node="https://api.s1.b.hmny.io/" one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw
```

**Comment by mindstyle85** [comment]
yes this works, i saw the reference that hmy means hmy.sh but then again all commands are given as ./hmy something 

should we change all commands to hmy.sh then?

**Comment by mindstyle85** [comment]
also balances doesnt work, balance works :) already fixed that in both pangaea and mainnet guide

**Comment by fxfactorial** [comment]
1. Re the naming change of balances, the linux binary is out of date, need to upload a new one. Basically just need to called `make upload-linux`. I think we might need to talk to @LeoHChen about giving p-ops some kind of credential that could upload new binary to s3 (if you see the make target, it assume a profile name of upload. 

2. We can change the docs, which is churn, or perhaps the better option is to statically build the binary (a fantastic task). HB has an example of how to statically link with BLS here: https://github.com/harmony-one/harmony/pull/1776

**Comment by mindstyle85** [comment]
I see, well the issue is once we let clients on testnet we have to have both binaries and guides in order, so there wont be confusion. We can get access yes, however some of us arent experienced enough in coding/building to be able to do some of these tasks, like the statically built binary. This is more something for @SebastianJ i think

**Comment by mindstyle85** [comment]
closed, we have the statically built binary now
