### ISSUE TITLE
hmy cli doesnt have chain-id implemented yet

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/pangaea-ops#2]
luka@ubuntu:~/Desktop/pangaea$ LD_LIBRARY_PATH=.  ./hmy --node="https://api.s1.b.hmny.io/" balance --chain-id="testnet" one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw
Error: unknown flag: --chain-id
luka@ubuntu:~/Desktop/pangaea$ LD_LIBRARY_PATH=.  ./hmy --node="https://api.s1.b.hmny.io/" --chain-id="testnet" balance  one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw
Error: unknown flag: --chain-id

Also checked the help, no such command in there, so no way to reach testnet right now?

CLI interface to the Harmony blockchain

Invoke 'hmy cookbook' for examples of the most common, important usages

Usage:
  hmy [flags]
  hmy [command]

Available Commands:
  balance     Check account balance
  blockchain  Interact with the Harmony.one Blockchain
  cookbook    Example usages of the most important, frequently used commands
  docs        Generate docs to a local hmy-docs directory
  help        Help about any command
  keys        Add or view local private keys
  transfer    Create and send a transaction
  version     Show version

Flags:
  -h, --help          help for hmy
  -e, --ledger        Use ledger hardware wallet
      --no-latest     Do not add 'latest' to RPC params
      --no-pretty     Disable pretty print JSON outputs
  -n, --node string   <host> (default "http://localhost:9500")

Use "hmy [command] --help" for more information about a command.

**Comment by fxfactorial** [comment]
This looks like the binary just has not been updated in a while, what does `./hmy.sh version` say

**Comment by mindstyle85** [comment]
Harmony (C) 2019. hmy, version v92-1979e78-dirty (haobo@harmony.one 2019-09-19T14:04:27-0700)

seems so, however i did update/install it today?

**Comment by fxfactorial** [comment]
that looks quite a bit old, mine already at v114. Someone has to upload the binary version updated for linux, that is the binary you pull down when you do `./hmy.sh -d`. I don't have a linux setup ready at the moment =/ But I pinged Haobo to update it later today

**Comment by mindstyle85** [comment]
yeah seems the repo has the old one, would be great if we have the new one so we can have the guides in order, and the binary, before we let clients onto the testnet.. 

And right now mainnet cant use it either right, since they cant pick mainnet to query balances?

**Comment by fxfactorial** [comment]
You choose which network to target via the node flag, aka the `--node="https://api.s1.b.hmny.io/" `, usage of --chain-id is for signing transactions.

**Comment by mindstyle85** [comment]
ah i see, so basically b = testnet and t = mainnet?

**Comment by fxfactorial** [comment]
right - its confusing to me as well

**Comment by mindstyle85** [comment]
got the chain-id from Janet, so naturally thought thats the way to choose which chain :D
