### ISSUE TITLE
External node never reached consensus, zerolog has : No peers, continue

### ISSUE THREAD

**Issue by sophoah** [harmony-one/pangaea-ops#4]
External nodes can't join consensus even after a full sync. 

once fully synched, it just keep synching new blocks every 30s or so :
DEBUG[11-14|13:06:16.170] Persisted trie from memory database      nodes=181 size=35.69kB time=2.04311ms  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:16.225] Persisted trie from memory database      nodes=182 size=35.97kB time=2.161503ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:16.404] Persisted trie from memory database      nodes=178 size=35.15kB time=2.193454ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:16.459] Persisted trie from memory database      nodes=186 size=36.59kB time=2.0427ms   gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:16.517] Persisted trie from memory database      nodes=183 size=36.08kB time=3.218415ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:16.577] Persisted trie from memory database      nodes=185 size=36.44kB time=2.26613ms  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:16.632] Persisted trie from memory database      nodes=184 size=36.26kB time=2.039284ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:45.944] Persisted trie from memory database      nodes=186 size=38.00kB time=1.814579ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:45.998] Persisted trie from memory database      nodes=188 size=38.26kB time=2.082716ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:46.051] Persisted trie from memory database      nodes=186 size=38.00kB time=2.12712ms  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:46.104] Persisted trie from memory database      nodes=188 size=38.26kB time=2.304163ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:46.157] Persisted trie from memory database      nodes=186 size=38.00kB time=2.008485ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:46.210] Persisted trie from memory database      nodes=188 size=38.26kB time=2.422907ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:46.269] Persisted trie from memory database      nodes=186 size=38.00kB time=2.168638ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-14|13:06:46.964] Persisted trie from memory database      nodes=188 size=38.26kB time=2.4672ms   gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B

here is the zerolog without what i think is without the DB synching logs, tail -f latest/zerolog-validator-212.47.229.123-9000.log | grep -v -E "Signers|Imported|Inserted|Member|SYNC|added" : 
https://pastebin.com/0pRr5Ujt

Here is another zerolog with no filter : https://pastebin.com/mXu6kzKh

From the leader, we can see from time to time the member message :
[ec2-user@ip-10-192-0-235 ~]$ tail -f latest/zerolog-validator-127.0.0.1-9000.log | grep 6420aeb6ffdbc7c03ab9d895b78090c6a4b8e1c8752d782cdf918c1fdea4b8991e3c1d2ee7a9037f9d0dc5a223353104
{"level":"info","port":"9000","ip":"127.0.0.1","index":42,"BlsPubKey":"6420aeb6ffdbc7c03ab9d895b78090c6a4b8e1c8752d782cdf918c1fdea4b8991e3c1d2ee7a9037f9d0dc5a223353104","caller":"/data/harmony/consensus/consensus_service.go:131","time":"2019-11-14T13:13:32.252904806Z","message":"Member"}
but never the consensus phase messages.

**Comment by sophoah** [comment]
root@harmony: ~ # ./node.sh -v
node.sh: version: v1 20191105.1
root@harmony: ~ # ./harmony -version
Harmony (C) 2019. harmony, version v4925-master-20191029.0-2-gb3eeed6b (jenkins@ 2019-10-30T03:21:17+0000)
root@harmony:~#

**Comment by JB273** [comment]
Same issue on my node;
root@JNB-Pangaea:/media/pangaea# ./node.sh -V
Harmony (C) 2019. harmony, version v4925-master-20191029.0-2-gb3eeed6b (jenkins@ 2019-10-30T03:21:17+0000)
root@JNB-Pangaea:/media/pangaea# ./node.sh -v
node.sh: version: v1 20191105.1
root@JNB-Pangaea:/media/pangaea# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Comment by mindstyle85** [comment]
@harmony-ek @LeoHChen we still have this issue open, basically "no peer, continue"

**Comment by sophoah** [comment]
to be tested in the new version but it should now be fixed. It seems like the bootstrapping order was wrong (aka it should be bootnode first then peer discovery, and not the reverse). 

@harmony-ek I'll close the case after confirming the devnet and next pangaea network is fine.

**Comment by yelllowsin** [comment]
Closing this one as we don't even have the pangaea network anymore and current OSTN doesn't have this issue anymore.
