### ISSUE TITLE
shrink/grow the root EBS volume of all testnet nodes

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/pangaea-ops#5]
I've noticed that we have launched testnet nodes using 100G EBS volume.  That's a waste of money as we are paying for every GB of EBS volume.  We don't need that much size to start with.  We need to have a tool to dynamically grow/shrink the size of the EBS volumes on testnet nodes.

@AndyBoWu had a script to start with, please try to adopt it for the testnet/pangaea network.

**Comment by AndyBoWu** [comment]
this issue has been addressed a while ago. this year, usually we just assign 15 GB for each node in our internal test networks.
