### ISSUE TITLE
Leader on shard2 remains the same, don´t change with epoch, more than 3-4 weeks

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/pangaea-ops#8]
Version-v5360-master-20191205.3-0-gefc0ae11
count:296

The leader from the shard 2 is currently : one1shzkj8tty2wu230wsjc7lp9xqkwhch2ea7sjhc 
[3.0.94.25:9500]  and is the same already for some weeks. (3-4 weeks)
--
The leader should change with epoch.

**Comment by mindstyle85** [comment]
@rlan35 @LeoHChen @harmony-ek 

escalating this one, totally forgot but since Eugene restarted, the above address is shard leader for most of the time, so at least 3-4 weeks if not even more

**Comment by BrunoMarshall** [comment]
I will close this issue, from Edgar information is not an issue if the leader stays several weeks in the leader position.
Thank you
