### ISSUE TITLE
 Testnet explorer is not showing the correct balance comparative to the staking dashboard

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/pangaea-ops#9]
The testnet explorer have currently some issues, is not showing the correct balance comparative to the staking dashboard.
Testnet explorer link: https://explorer.testnet.harmony.one/#/
Staking explorer link: https://staking.harmony.one/networks

For example check the balance for the wallet address in both platforms: one154tuzu7a45y0qu07lwlhrp8askfnr0gz5gwtye
![image](https://user-images.githubusercontent.com/35432495/70340730-a2be0080-1851-11ea-8694-6116d4607c3f.png)
and in the staking explorer:
![image](https://user-images.githubusercontent.com/35432495/70341273-e06f5900-1852-11ea-830a-c9f3079a3b86.png)

**Comment by mattlockyer** [comment]
@BrunoMarshall can confirm this is due to testnet upgrades. We're also updating the tooling, staking dashboard and explorer. Check with us in Discord for updates. Thank you for raising this issue!
